name: Check automated branches

on:
  # zizmor: ignore[dangerous-triggers]
  pull_request_target:
    branches:
      - main
      - latest
      - examples

permissions: {}

jobs:
  notice:
    name: Notice for automated branches
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Comment on pull request
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const {issue:{number:issue_number}, repo:{owner, repo}} = context
            github.rest.issues.createComment({issue_number, owner, repo, body:[
              "Hello there ðŸ‘‹!",
              "",
              "It seems you have opened a pull request on either `main`, `latest` or `examples`.",
              "These branches are fully-automated and do not accept human contributions.",
              "",
              "* To contribute to *metrics* code, open a pull request to `master` branch",
              "* To contribute to *metrics* presets, open a pull request to `presets` branch",
              "",
              "Thanks for your cooperation ðŸ¦¾!"
            ].join("\n")})
      - name: Fail workflow
        run: exit 1
