name: Publish examples (presets)
on:
  schedule:
    - cron: "0 16 1/2 * *"
  workflow_dispatch:
  workflow_call:

permissions: {}

jobs:
  examples:
    runs-on: ubuntu-latest
    if: github.repository == 'gh-metrics/metrics'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20
      - name: Setup metrics
        run: npm ci
      - name: Publish presets examples
        # zizmor: ignore[use-trusted-publishing] False-positive.
        run: npm run presets -- publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
