name: Label issue and pull requests

on:
  # zizmor: ignore[dangerous-triggers] Just labels, no code execution.
  pull_request_target

permissions: {}

jobs:
  label:
    name: Label issue and pull requests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/config/label.yml
          sync-labels: yes
