name: Stale issues, pr and runs

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  stale:
    name: Flag stale issues and pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
        with:
          days-before-stale: -1
          stale-pr-message: This pull request seems to be inactive and will be automatically closed in a few days if it remains without any activity.
          days-before-pr-stale: 90
          days-before-pr-close: 7
          stale-pr-label: ‚èπÔ∏è stale
          remove-stale-when-updated: yes
          exempt-issue-labels: üì¶ dependencies
  lock:
    name: Lock inactive closed issues and pull requests
    needs:
      - stale
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771 # v5
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: 180
          issue-lock-reason: ""
          add-issue-labels: ‚òëÔ∏è archived
          pr-inactive-days: 180
          pr-lock-reason: ""
          add-pr-labels: ‚òëÔ∏è archived
  workflows:
    name: Remove expired workflow runs
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Run script
        run: ./delete_workflows.sh gh-metrics/metrics
        working-directory: .github/actions/ghcr-clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
